name: Go Test
on: [push]
env:
  SAMWISE_CLI_GIT_SSH_KEY_PATH: ${{secrets.SAMWISE_CLI_GIT_SSH_KEY_PATH}}
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version: '1.22.x'
            - name: Install dependencies
              run: go get .
            - name: Build
              run: go build -v ./...
            - name: setup ssh key for testing
              run: |
                      mkdir test_dir
                      echo '${{ secrets.SSH_PRIVATE }}' > test_dir/id_rsa
            - name: Test with the Go CLI
              run: go test -json ./cmd/...
                